name : Auto Deploy To vercel 

on:
    push:
        branches:
            - main 

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest   
        steps:
            - name: Download Source Code 
              uses:  actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                
            - name: Install Project packages 
              run: npm install    

            - name: Build the Project 
              run: npm run build 
              
            - name: Deploy the Vercel 
              run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}  


